'use client';
import Link from 'next/link';
import { ArrowUpRight, Package, ShoppingBag, Link2, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useI18n } from '@/lib/support/i18n';
import { PRODUCTS, ORDER, ORDERS, CART, productUrl } from '@/lib/support/preview-data';
import type { VisitorContext } from '@/lib/support/preview-data';
export function ProductArt({id,large=false}:{id:string;large?:boolean}){return <div aria-hidden="true" className={'product-art '+(large?'large ':'')+id}>{id==='field-tee'?<svg viewBox="0 0 120 120"><path d="M38 20 20 28 7 53 27 63 32 52 32 103 88 103 88 52 93 63 113 53 100 28 82 20Q60 35 38 20Z" fill="#333c35" stroke="#85907f" strokeWidth="1"/><path d="M46 23Q60 40 74 23" fill="none" stroke="#83917f"/><text x="60" y="65" textAnchor="middle" fill="#d5e2c5" fontSize="12" fontFamily="Arial" letterSpacing="2">AF</text></svg>:<svg viewBox="0 0 120 120"><rect x="28" y="36" width="64" height="65" rx="12" fill="#7c8073"/><ellipse cx="60" cy="37" rx="32" ry="9" fill="#aaa99c"/><ellipse cx="60" cy="31" rx="33" ry="8" fill="#c1c1b2"/><text x="60" y="76" textAnchor="middle" fill="#30372d" fontSize="15" fontFamily="Arial" letterSpacing="2">AF</text></svg>}</div>;}
export function ProductCard({id,shared=false,send}:{id:string;shared?:boolean;send?:(body:string)=>Promise<unknown>}){
 const {t,locale}=useI18n(),product=PRODUCTS.find(p=>p.id===id);if(!product)return null;
 return <div className={'commerce-card '+(shared?'shared-card':'')}><div className="commerce-product"><ProductArt id={id}/><div><span className="micro-label">{t('Sample')} / {t('Product details')}</span><strong>{product.name}</strong><p>{product.detail[locale]}</p><b>฿{product.price.toLocaleString(locale)}</b></div></div><Link className="commerce-link" href={'/products/'+id} target="_blank">{t('View product preview')}<ArrowUpRight size={14}/></Link>{send&&<Button className="context-send" onClick={()=>void send(productUrl(id))}><Link2 size={15}/>{t('Share product')}</Button>}</div>;
}
export function OrderCard({send,id=ORDER.id}:{send?:(body:string)=>Promise<unknown>;id?:string}){const {t}=useI18n(),order=ORDERS.find(item=>item.id===id)||ORDER;return <div className="commerce-card order-card"><div className="card-title"><Package size={19}/><span>{t('Order')}</span><small>{t('Sample')}</small></div><strong className="order-id">{order.id}</strong><span className="order-status">{t(order.status)}</span><p>{order.placedAt} · {order.items.reduce((sum,item)=>sum+item.quantity,0)} {t('Items')} · ฿{order.total.toLocaleString()}</p>{send&&<Button className="context-send" onClick={()=>void send('[af-order:'+order.id+']')}>{t('Ask about this order')}<ArrowUpRight size={15}/></Button>}</div>;}
export function CartCard({send}:{send?:(body:string)=>Promise<unknown>}){const {t}=useI18n();return <div className="commerce-card"><div className="card-title"><ShoppingBag size={19}/><span>{t('Cart')}</span><small>{t('Sample')}</small></div>{CART.map(item=><div key={item.productId} className="cart-line"><ProductArt id={item.productId}/><div><strong>{PRODUCTS.find(p=>p.id===item.productId)?.name}</strong><span>× {item.quantity} · ฿840</span></div></div>)}{send&&<Button className="context-send" onClick={()=>void send('[af-cart:preview]')}>{t('Share cart')}<ArrowUpRight size={15}/></Button>}</div>;}
export function ContextPanel({context,send,login,agent=false}:{context:VisitorContext;send?:(body:string)=>Promise<unknown>;login?:()=>void;agent?:boolean}){
 const {t}=useI18n();return <div className="context-panel">
 <div className="context-section"><h3>{t(agent?'Customer activity':'Your details')}</h3><span className="source-label">{t('Source page')}</span><div className="source-value">{context.sourcePage||t('Direct visit')}</div></div>
 {context.productId&&<div className="context-section"><h3>{t('Currently viewing')}</h3><ProductCard id={context.productId} send={send}/></div>}
 <div className="context-section"><div className="member-heading"><UserRound size={19}/><strong>{t(context.member?'Sample member':'Member account')}</strong></div>{context.member?<><div className="member-identity"><span>AM</span><div><strong>Alex Morgan</strong><small>{t('Sample member')} · AF / 001</small></div></div><OrderCard send={send}/><CartCard send={send}/></>:<><p className="context-muted">{t(agent?'No shared context yet.':'Sign in to preview your orders and cart.')}</p>{login&&<Button variant="outline" onClick={login}>{t('Sign in')}<ArrowUpRight size={15}/></Button>}</>}</div>
 {!agent&&!context.productId&&<div className="context-section"><h3>{t('Product page preview')}</h3><Link href="/products/field-tee" className="product-preview-link"><ProductArt id="field-tee"/><span>AF / Field Tee<small>{t('Ask about this product')}</small></span><ArrowUpRight size={16}/></Link></div>}
 <p className="context-disclaimer">{t('Member, order and cart data are samples.')}</p></div>;
}
