'use client';
import { useEffect, useState } from 'react';
import { Plus, Trash2, Check, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { useI18n, languages } from '@/lib/support/i18n';
import { localized } from '@/lib/support/preview-data';
import type { SupportSettings as Config, ContentLanguage } from '@/lib/support/preview-data';
function normalizeConfig(value:Config):Config{const next=structuredClone(value);next.articles=(next.articles||[]).map(article=>({...article,keywords:Array.isArray(article.keywords)?article.keywords:[],autoReply:article.autoReply===true,responseType:article.responseType||'answer',options:Array.isArray(article.options)?article.options:[]}));return next;}
export function SupportSettings({initial,save}:{initial:Config;save:(data:Config)=>Promise<void>}){
 const {t,locale}=useI18n(),[draft,setDraft]=useState(()=>normalizeConfig(initial)),[tab,setTab]=useState('replies'),[language,setLanguage]=useState<ContentLanguage>(locale),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=sessionStorage.getItem('af-settings-draft');if(raw){const value=JSON.parse(raw) as Config;if(Array.isArray(value.quickReplies)&&Array.isArray(value.articles)&&value.welcome&&value.away)queueMicrotask(()=>{setDraft(normalizeConfig(value));setDirty(true);});}}catch{}},[]);
 function change(fn:(data:Config)=>void){const next=structuredClone(draft);fn(next);setDraft(next);setDirty(true);setSaved(false);try{sessionStorage.setItem('af-settings-draft',JSON.stringify(next));}catch{}}
 async function commit(){setBusy(true);setError('');try{await save(draft);setDirty(false);setSaved(true);try{sessionStorage.removeItem('af-settings-draft');}catch{}}catch{setError(t('Save failed. Please try again.'));}finally{setBusy(false);}}
 return <div className="settings-page"><header className="settings-heading"><div><span className="micro-label">ALIEN FARMERS / {t('Operations')}</span><h1>{t('Settings')}</h1><p>{t('Save settings to apply them to this local preview.')}</p></div><Button onClick={()=>void commit()} disabled={busy||!dirty}>{saved?<Check size={16}/>:<Save size={16}/>} {t(saved?'Saved':'Save changes')}</Button></header>
 {dirty&&<p className="settings-status">{t('Unsaved changes')}</p>}{error&&<p role="alert" className="inline-error">{error}</p>}
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="settings-tabs" variant="line"><TabsTrigger value="replies">{t('Quick replies')}</TabsTrigger><TabsTrigger value="auto">{t('Auto replies')}</TabsTrigger><TabsTrigger value="knowledge">{t('Knowledge base')}</TabsTrigger></TabsList></Tabs>
 {tab!=='knowledge'&&<label className="content-language">{t('Content language')}<select value={language} onChange={e=>setLanguage(e.target.value as ContentLanguage)}>{Object.entries(languages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
 {tab==='replies'&&<div className="settings-cards">{draft.quickReplies.map((r,index)=><section className="settings-card" key={r.id}><div className="settings-card-top"><label>{t('Title')}<Input aria-label={t('Title')+' '+(index+1)} maxLength={150} value={r.title} onChange={e=>change(d=>{d.quickReplies[index].title=e.target.value;})}/></label><Button variant="ghost" size="icon" aria-label={t('Delete')+' '+r.title} onClick={()=>change(d=>{d.quickReplies.splice(index,1);})}><Trash2 size={17}/></Button></div><label>{t('Answer')} · {languages[language]}<textarea maxLength={4000} value={r.bodies[language]} onChange={e=>change(d=>{d.quickReplies[index].bodies[language]=e.target.value;})}/></label></section>)}{!draft.quickReplies.length&&<p>{t('No replies yet. Add your first answer.')}</p>}<Button variant="outline" disabled={draft.quickReplies.length>=40} onClick={()=>change(d=>{d.quickReplies.push({id:crypto.randomUUID(),title:t('Add reply'),bodies:localized('','','','','')});})}><Plus size={17}/>{t('Add reply')}</Button></div>}
 {tab==='auto'&&<div className="settings-cards">{(['welcome','away'] as const).map(key=><section className="settings-card" key={key}><div className="auto-rule-heading"><div><h2>{t(key==='welcome'?'Welcome reply':'Away reply')}</h2><p>{t(key==='welcome'?'Send once after the first visitor message.':'Send when no agent is online; at most once every 15 minutes.')}</p></div><Switch checked={draft[key].enabled} aria-label={t('Enable')+' '+t(key==='welcome'?'Welcome reply':'Away reply')} onCheckedChange={checked=>change(d=>{d[key].enabled=checked;})}/></div><label>{t('Answer')} · {languages[language]}<textarea maxLength={4000} value={draft[key].bodies[language]} onChange={e=>change(d=>{d[key].bodies[language]=e.target.value;})}/></label></section>)}</div>}
 {tab==='knowledge'&&<div className="settings-cards">{draft.articles.map((a,index)=><section className="settings-card" key={a.id}><div className="settings-card-top"><label>{t('Title')}<Input aria-label={t('Title')+' '+(index+1)} value={a.title} maxLength={150} onChange={e=>change(d=>{d.articles[index].title=e.target.value;})}/></label><Button variant="ghost" size="icon" aria-label={t('Delete')+' '+a.title} onClick={()=>change(d=>{d.articles.splice(index,1);})}><Trash2 size={17}/></Button></div><label>{t('Keywords')}<Input maxLength={800} placeholder={t('Separate keywords with commas')} value={a.keywords.join(', ')} onChange={e=>change(d=>{d.articles[index].keywords=e.target.value.split(/[,，]/).map(k=>k.trim()).slice(0,30);})}/></label><label>{t('Response type')}<select value={a.responseType} onChange={e=>change(d=>{d.articles[index].responseType=e.target.value as Config['articles'][number]['responseType'];})}><option value="answer">{t('Direct answer')}</option><option value="options">{t('Multiple choice')}</option><option value="order_lookup">{t('Look up customer orders')}</option></select></label><label>{t(a.responseType==='options'?'Question':'Article content')}<textarea maxLength={4000} value={a.body} onChange={e=>change(d=>{d.articles[index].body=e.target.value;})}/></label>{a.responseType==='options'&&<label>{t('Options')}<textarea maxLength={2000} placeholder={t('One option per line')} value={a.options.join('\n')} onChange={e=>change(d=>{d.articles[index].options=e.target.value.split('\n').slice(0,10);})}/></label>}<div className="knowledge-switches"><label className="publish-toggle"><Switch checked={a.published} aria-label={t('Publish for agents')} onCheckedChange={checked=>change(d=>{d.articles[index].published=checked;})}/>{t(a.published?'Published':'Draft')}</label><label className="publish-toggle"><Switch checked={a.autoReply} aria-label={t('Automatic keyword reply')} onCheckedChange={checked=>change(d=>{d.articles[index].autoReply=checked;})}/>{t('Automatic keyword reply')}</label></div></section>)}{!draft.articles.length&&<p>{t('No articles yet.')}</p>}<Button variant="outline" disabled={draft.articles.length>=40} onClick={()=>change(d=>{d.articles.push({id:crypto.randomUUID(),title:t('Add article'),body:'',published:false,keywords:[],autoReply:false,responseType:'answer',options:[]});})}><Plus size={17}/>{t('Add article')}</Button></div>}
 </div>;
}
