import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
void test('customer support uses a server-only integration and stable signed visitor identity',async()=>{const [session,route,hook]=await Promise.all([read('lib/support/cloud-session.ts'),read('app/api/support/conversation/[id]/messages/route.ts'),read('hooks/use-cloud-support.ts')]);assert.match(session,/CHAT_SERVICE_TOKEN/);assert.match(session,/CHAT_VISITOR_COOKIE='af_chat_visitor'/);assert.match(session,/HttpOnly; SameSite=Lax/);assert.match(route,/isSameOrigin/);assert.match(hook,/setInterval\(\(\)\s*=>\s*void refresh\(\), 3000\)/);});
void test('all four live channels show only persisted messages and isolate member drafts',async()=>{const [view,route,hook]=await Promise.all([read('components/support/visitor-terminal.tsx'),read('app/api/support/conversation/route.ts'),read('hooks/use-cloud-support.ts')]);assert.match(view,/const isCloud=selectedId==='customer-support'\|\|Boolean\(memberChannel\)/);assert.match(view,/messages:selectedCloud\.conversation\?\.messages\|\|\[\]/);for(const channel of ['delivery','feedback_private','wholesale'])assert.match(view,new RegExp(`useCloudSupport\\(locale,'${channel}',access==='member'&&Boolean\\(memberId\\)`));assert.match(route,/sourceSite:'chat',channel/);assert.match(hook,/channel=\$\{channel\}/);assert.match(hook,/wire\?\.identityKey === identityKey/);assert.match(view,/feedback:feedbackCloud\.conversation\|\|blankCloudConversation/);assert.match(view,/delivery:deliveryCloud\.conversation\|\|blankCloudConversation/);assert.match(view,/wholesale:wholesaleCloud\.conversation\|\|blankCloudConversation/);assert.match(view,/setMemberDrafts\(\{\}\)/);assert.match(hook,/pending\.current\?\.identityKey === identityKey/);});
void test('cloud channels never fall back to unsent local messages when the API is unavailable',async()=>{const [view,composer]=await Promise.all([read('components/support/visitor-terminal.tsx'),read('components/assistant-chat/message-composer.tsx')]);assert.match(view,/selectedCloudConnected=Boolean\(selectedCloud\.conversation\)&&!selectedCloud\.error/);assert.match(view,/if\(!selectedCloudConnected\)return/);assert.match(view,/sendDisabled=\{unreleased\|\|\(isCloud&&!selectedCloudConnected\)\}/);assert.match(composer,/disabled=\{Boolean\(disabledReason\)\|\|sendDisabled\|\|!value\.trim\(\)\}/);});
void test('unreleased channels cannot submit local messages and the widget opens real support',async()=>{const [view,window,widget]=await Promise.all([read('components/support/visitor-terminal.tsx'),read('components/assistant-chat/chat-window.tsx'),read('components/assistant-chat/floating-chat.tsx')]);assert.match(view,/if\(unreleased\)return/);assert.match(window,/onAction=\{unavailable\?undefined:onAction\}/);assert.match(window,/disabledReason=\{unavailable\?/);assert.match(widget,/const assistantId = 'af-ai'/);assert.match(widget,/window\.top\.location\.href = url/);assert.doesNotMatch(widget,/center\.select\('customer-support'\)/);});
void test('legacy Chat operations routes hand off to the Staff support workspace',async()=>{const [home,ops,settings,target]=await Promise.all([read('app/page.tsx'),read('app/ops/page.tsx'),read('app/ops/settings/page.tsx'),read('lib/support/staff-origin.ts')]);assert.doesNotMatch(home,/ops\.alienfarmers\.org|OpsInbox/);assert.match(ops,/redirect\(staffSupportUrl\(\)\)/);assert.match(settings,/redirect\(staffSupportUrl\(\)\)/);assert.match(target,/staff\.alienfarmers\.org/);});
