'use client';
import { useRef } from 'react';
import { ArrowUp, LockKeyhole } from 'lucide-react';
import { assistantText } from '@/lib/assistant-chat/copy';
import { useI18n } from '@/lib/support/i18n';
export function MessageComposer({assistantId,value,onChange,onSend,privateChannel=false,cloudChannel=false,cloudPersisted=false,sendDisabled=false,disabledReason}:{assistantId:string;value:string;onChange:(value:string)=>void;onSend:()=>void;privateChannel?:boolean;cloudChannel?:boolean;cloudPersisted?:boolean;sendDisabled?:boolean;disabledReason?:string}){
 const {locale}=useI18n(),copy=(text:string)=>assistantText(text,locale),ref=useRef<HTMLTextAreaElement>(null);
 return <div className="assistant-composer-wrap"><div className="assistant-composer"><label className="sr-only" htmlFor={'assistant-composer-'+assistantId}>{copy('Message')}</label><textarea ref={ref} id={'assistant-composer-'+assistantId} rows={1} maxLength={4000} value={value} disabled={Boolean(disabledReason)} placeholder={copy(disabledReason?'Coming soon':'Write a message…')} onChange={event=>onChange(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();if(!sendDisabled&&!disabledReason)onSend();}}}/><button onClick={onSend} disabled={Boolean(disabledReason)||sendDisabled||!value.trim()} aria-label={copy('Send message')}><ArrowUp size={20}/></button></div><div className="assistant-composer-note">{disabledReason?<span>{copy(disabledReason)}</span>:privateChannel?<span><LockKeyhole size={12}/>{copy('Visible only to Owner and Admin')}</span>:<span>{copy('Enter to send · Shift + Enter for a new line')}</span>}<span>{value.length>3500?value.length+' / 4000':copy(cloudChannel?(cloudPersisted?'Saved in Conversation Center':'Connect to send'):'Stored on this device')}</span></div></div>;
}
