'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { AssistantConversation,ChatMessage } from '@/lib/assistant-chat/types';
type WireMessage={id:string;sender_type:'visitor'|'member'|'staff'|'system';body:string;created_at:string};
type WireConversation={id:string;status:'waiting'|'open'|'closed';messages:WireMessage[]};
function mapped(value:WireConversation):AssistantConversation{return{messages:value.messages.map((message):ChatMessage=>({id:message.id,sender:message.sender_type==='staff'?'staff':message.sender_type==='system'?'system':'user',body:message.body,createdAt:message.created_at})),unread:0,updatedAt:value.messages.at(-1)?.created_at||new Date().toISOString(),draft:'',conversationStatus:value.status==='closed'?'closed':value.status==='waiting'?'waiting':'active'};}
export function useCloudSupport(locale:string){const [wire,setWire]=useState<WireConversation|null>(null),[error,setError]=useState(''),[sending,setSending]=useState(false),mounted=useRef(true);
 const refresh=useCallback(async()=>{try{const response=await fetch(`/api/support/conversation?locale=${encodeURIComponent(locale)}`,{cache:'no-store'}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||'Support unavailable');if(mounted.current){setWire(payload.data);setError('');}}catch(reason){if(mounted.current)setError(reason instanceof Error?reason.message:'Support unavailable');}},[locale]);
 useEffect(()=>{mounted.current=true;void refresh();const timer=setInterval(()=>void refresh(),3000);return()=>{mounted.current=false;clearInterval(timer);};},[refresh]);
 const send=useCallback(async(body:string)=>{if(!wire||!body.trim()||sending)return false;setSending(true);try{const response=await fetch(`/api/support/conversation/${encodeURIComponent(wire.id)}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:body.trim(),clientMessageId:crypto.randomUUID(),locale,sourceSite:'chat'})}),payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||'Message could not be sent.');await refresh();return true;}catch(reason){setError(reason instanceof Error?reason.message:'Message could not be sent.');return false;}finally{setSending(false);}},[locale,refresh,sending,wire]);
 return{conversation:wire?mapped(wire):null,error,sending,refresh,send};}
